# Acesso ao repositório privado referenciando o secret para obtenção da imagem no arquivo de manifesto Pod
apiVersion: v1
kind: Pod
metadata:
	name: kuard-tls
spec:
	containers:
		- name: kuard-tls
			images: gcr.io/kuar-demo/kuard-amd64:blue
			imagePullPolicy: Always
			volumeMounts:
				- name: tls-certs
					mountPath: "/tls"
					readOnly: True
		imagePullSecrets:
			- name: my-image-pull-secrets
		volume:
			- name: tls-cert	
			secret:
				secretName: kuard-tls

