# Declaração um volume de secrets que esponha o secret "kuard-tls" ao contêiner kuard em "/tls"
apiVersion: v1
kind: Pod
metadata:
	name: kuard-tls
spec:
	containers:
		- name: kuard-tls
			images: gcr.io/kuar-demo/kuard-amd64:blue
			imagePullPolicy: Always
			volumeMounts:
				- name: tls-certs
					mountPath: "/tls"
		volumes:
			- name: tls-certs
				secret:
					secretName: kuard-tls

