# Perfil simples que atribui a uma identidade a aptidão de criar e modificar Pods e serviços
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-and-services
rules:
  - apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]