apiVersion: v1
kind: Pod
metadata:
	name: kuard
spec:
	containers:
		- images: gcr.io/kuar-demo/kuard-amd64:blue
			name: kuard
			# limite mínimo
			# Faz com que o contêiner seja colocado em uma máquina com metade de uma CPU livre e 128MB de memória alocada para ele.
			resources:
				requests:
					cpu: "500m"
					memory: "128Mi"
			ports:
		  	- containerPort: 8080
		  	  name: http
		  	  protocol: TCP

