apiVersion: extensions/v1beta1
kind: Secret
# especificar um secret (dados sigilosos) com seu certificado TLS e chaves
metadata:
  creationTimestamp: null
  name: tls-secret-name
type: kubernetes.io/tls
data:
tls.crt: <base64 encoded certificate>
tls.key: <base64 encoded private key>
  