# Limitando o NGINX para que execute apenas nos nós com o rótulo "ssd=true" definido.
apiVersion: extensions/v1beta1
kind: "DaemonSet"
metadata:
	name: fluentd
	labels:
		app: nginx
		ssd: true
		name: nginx-fast-storage
spec:
	template:
		metadata:	
				labels:
					app: nginx
					ssd: "true"
		spec:
			nodeSelector:
				ssd: "true"
			containers:
			 - name: nginx
				 image: nginx:1.10.0