apiVersion: v1
kind: ReplicaSet
# nome único para cada Pod
metadata:
	name: kuard
# descreve o número de Pods (réplicas) que executarão no cluster
spec:
	replicas: 1
	template:
		metadata:	
			labels:
				app: kuard
				version: "2"
	spec:
		containers:
			- name: kuard
				image: "gcr.io/kuar-demo/kuard-amd64:green"

