apiVersion: v1
kind: Service
# criar um serviço "headless", ou seja, sem endereço virtual
metadata:
  name: mongo
spec:
  ports:
  - port: 21017
    name: peer
  clusterIP: None
  selector:
    app: mongo