apiVersion: storage.k8s.io/v1
kind: StorageClass
# classe de armazenagem que provisionará automaticamente objetos para disco na plataforma microsoft Azure
metadata:
  name: default
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
    kubernetes.io/cluster-service: "true"
  provisioner: kubernetes.io/azure-disk
